name: Delivery

on:
  push:
    branches: [ master, ubereats ]

jobs:
  loopcheck:
    strategy:
      matrix:
        watchers: [meals-ruby,meals-go,meals-java]
    runs-on: [ubuntu-latest]
    steps:
#       - name: dispatch
#         run: |
#           echo ${{ matrix.watchers }}
      - uses: actions/checkout@v2
      - name: dispatch
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/EmojiMeals/${{ matrix.watchers }}/dispatches --data '{"event_type": "build_application"}'
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          # A repo scoped GitHub Personal Access Token
          token: ${{ secrets.access_token }}
          # The full name of the repository to send the dispatch. Defaults to the current repository.
          repository: EmojiMeals/${{ matrix.watchers }}
          # A custom webhook event name.
          event-type: recipe_dispatch
          # JSON payload with extra information about the webhook event that your action or worklow may use.
      
