name: Delivery

on:
  push:
    branches: [ master, ubereats ]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls
      - name: dispatch to watchers
        env:
          WATCHERS: |
            - meals-ruby
            - meals-go
            - meals-java
        run: for w in $WATCHERS; do echo w; done
        
