name: Delivery

on:
  push:
    branches: [ master, ubereats ]

jobs:
  loopcheck:
    strategy:
      matrix:
        watchers: [meals-ruby,meals-go,meals-java]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.access_token }}
          # The full name of the repository to send the dispatch. Defaults to the current repository.
          repository: EmojiMeals/${{ matrix.watchers }}
          # A custom webhook event name.
          event-type: recipe-dispatch
          # JSON payload with extra information about the webhook event that your action or worklow may use.
          payload: recipes.json
